version: "3.9"
services:
  db:
    image: postgres
    env_file:
      - .env.prod
    volumes:
      - jobgate_db_data:/var/lib/postgresql/data
  backend:
    image: othmanmallah/jobgate-backend:latest
    env_file:
      - .env.prod
    ports:
      - 8000:8000
    restart: always
    volumes:
      - static_volume:/jobgate/stati
    depends_on:
      - db
      - front
      - redis
  front:
    image: tchtaibi/jobgate-frontend:latest
    # ports:
    #   - 3000:3000
    restart: always
  redis:
    image: redis
    restart: always
  nginx :
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - front
  flower:
    image: mher/flower
    container_name: flower
    command: celery flower
    env_file:
      - .env.flower
    # ports:
    #   - 9000:9000
    depends_on:
      - redis
    volumes:
      - flower:/data

volumes:
  jobgate_db_data:
  static_volume:
  flower: